### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by ps2cho** [khk4912/BGM-Discord-Bot#1]
[<commands.chatting.chatting object at 0x756c5c90>, <commands.admin.admin object at 0x756c5cd0>, <commands.cc.cc object at 0x756c5d30>, <commands.afk.afk object at 0x756c5d70>, <commands.owner.owner object at 0x756c5db0>, <commands.money.money object at 0x756c5e10>] 

Traceback (most recent call last):
  File "main.py", line 147, in <module>
    client = Bot()
  File "main.py", line 23, in __init__
    self.set_black()
  File "main.py", line 28, in set_black
    self.blacklist = pickle.load(f)
EOFError: Ran out of input

딱히 건드린건 명령어 이름 등 밖에 없고 실행해보려는데 이렇게 뜨네요.. 어떻게 하나요?

**Comment by khk4912** [comment]
업로드된 pickle 파일의 문제로 보이며 추후 blacklist.pickle 파일을 재업로드 하도록 하겠습니다.
